Add Reports

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,54 @@
-version: 2.1
-orbs:
-  node: circleci/node@3.0.0
+version: 2
+jobs:
+  node/test:
+    docker:
+    - image: cimg/node:13.11.0
+    steps:
+    - checkout
+    - run:
+        command: |
+          if [ ! -f "package.json" ]; then
+            echo
+            echo "---"
+            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+            echo "---"
+            echo
+            echo "Current directory: $(pwd)"
+            echo
+            echo
+            echo "List directory: "
+            echo
+            ls
+            exit 1
+          fi
+        name: Checking for package.json.
+        working_directory: ~/project
+    - restore_cache:
+        keys:
+        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
+    - run:
+        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
+        name: Installing NPM packages
+        working_directory: ~/project
+    - save_cache:
+        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
+        paths:
+        - ~/.npm
+    - run: 
+        command: mkdir ~/report
+        
+    - run:
+        command: npm run test
+        name: Run NPM Tests
+        working_directory: ~/project
+        environment:
+          MOCHA_FILE: ~/report/test-results.xml
+    - store_test_results:
+        path: ~/reports
+    - store_artifacts:
+        path: ~/reports
 workflows:
   node-tests:
     jobs:
-      - node/test
+    - node/test
+  version: 2
